FROM python

WORKDIR /sum

COPY ./sum.py .

# if want to read externel file. and copy the file as absolute path. if not work try /user/nayeem/file location.txt
# COPY ./read-flie-name.txt .

# for installing package
# RUN pip install package-name

CMD ["python", "sum.py"]